### ISSUE TITLE
`copyWith` probably handles nulls incorrectly

### ISSUE THREAD

**Issue by ildarsharafutdinov** [marcelgarus/data_classes#3]
hi, 
I'm looking into your example and I guess nulls do not work properly(I didn't run it though).

```
  var me = const User(firstName: 'Marcel', lastName: 'Garus', photoUrl: 'http://example.com');
  var mySister = me.copyWith(firstName: 'Yvonne', photoUrl: null);
```

`photoUrl` is updated as follows `photoUrl: photoUrl ?? this.photoUrl,` which leads to `mySister.photoUrl == 'http://example.com'` instead of null.

**Comment by marcelgarus** [comment]
That is indeed true, because if a parameter to the method is `null`, it doesn't know if it has been explicitly or implicitly set to `null`. I thought about this before but found no easy way to fix that.
Here are more complicated ways I considered:

On the client code side you can of course convert it to a mutable, the set the fields, then re-convert it to the immutable. Doesn't change the fact that the `copyWith` method behaves unintuitive in some cases.

Change the signature to expect a function for nullable values (just like `Iterable`'s `firstWhere(..., orElse: () => otherValueWhichMayBeNull)`).
However that leads to code that's a little bit uglier:
```dart
mySister = me.copyWith(
  firstName: 'Yvonne',
  photoUrl: () => null,
)
```

Third solution, add default values just like `dart:ui`'s `hashValues()` function, which is defined as
```dart
const _default = Object();
int hashValues(Object arg1, [Object arg2 = _default, ...])
```
In the code you can check if `_default == _arg2`, so you can see if the user explicitly passed in `null`. Something like this would probably be the most elegant solution, but we'd need "sample objects" of all the Field's types as default parameter values and that's at least as far as I know impossible to achieve.

If anyone has any other suggestions on how to do this elegantly, you're welcome to share your thoughts.

**Comment by marcelgarus** [comment]
You're right.

What about we always have a builder method for mutations but if your class has only non-nullable fields, you can optionally explicitly ask for the `copyWith` method in the annotation, something like `@DataClass(generateCopyWith=true)`.

And if the class contains nullable fields, that will be an error during code generation.

**Comment by ildarsharafutdinov** [comment]
I'm still in favor of `copyWith((mutable) => ...)` :)

E.g. requirements change and a field becomes nullable. A developer will need to remove `generateCopyWith=true` and then modify all fancy calls of `copyWith`.
Whereas `copyWith((mutable) => ...)` won't require changes in existing code.

**Comment by marcelgarus** [comment]
Hmm that is indeed true...
Okay, I'll implement it that way.

**Comment by marcelgarus** [comment]
Done. The newest version 2.0.0, already [published on pub](https://pub.dev/packages/data_classes), generates a `copy` method allowing usage like this:
```dart
var freshApple = const Fruit(type: 'apple', color: 'green');
var someApple = freshApple.copy((fruit) => fruit..color = null);
var kiwi = someApple.copy((fruit) => fruit
  ..type = 'Kiwi'
  ..color = 'brown');
```
The definition looks like this:
```dart
/// Copies this [Fruit] with some changed attributes.
Fruit copy(void Function(MutableFruit mutable) changeAttributes) {
  assert(
      changeAttributes != null,
      "You called Fruit.copy, but didn't provide a function for changing "
      "the attributes.\n"
      "If you just want an unchanged copy: You don't need one, just use "
      "the original.");
  var mutable = this.toMutable();
  changeAttributes(mutable);
  return Fruit.fromMutable(mutable);
}
```
